### ISSUE TITLE
can i use scrollview or other view in fragment.

### ISSUE THREAD

**Issue by BlackJia** [hearsilent/Universal-CollapsingTabLayout#1]

**Comment by hearsilent** [comment]
You should use `NestedScrollView` instead of `ScrollView`, and add `app:layout_behavior="@string/appbar_scrolling_view_behavior"`.

Hope you can work successfully :)

**Comment by hearsilent** [comment]
Other view just add `app:layout_behavior="@string/appbar_scrolling_view_behavior"` the same.

**Comment by hearsilent** [comment]
@BlackJia Let me know if you work successful!
